language: php
php:
    - 7.0
    - 5.6
    - 5.5
    - hhvm

env:
    - DB=mysql MYSQL_USER=root MYSQL_PASSWORD="" MYSQL_HOST=127.0.0.1 MYSQL_PORT=3306 MYSQL_DBNAME=knit_test
    - MONGODB=1 MONGODB_user="" MONGODB_PASSWORD="" MONGODB_HOST=127.0.0.1 MONGODB_PORT=27017 MONGODB_DBNAME=knit_test

services:
    - mongodb

before_script:
    - make install

script:
    - make qa

notifications:
    email:
        - michal@michaldudek.pl
